# Build the manager binary
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:96cfceb50f5323efa1aa8569d4420cdbf1bb391225d5171ef72a0d0ecf028467 as builder

WORKDIR /workspace
COPY . .
# Build
RUN CGO_ENABLED=1 go build -a -o manager main.go

FROM registry.redhat.io/rhel9-2-els/rhel:9.2@sha256:dd3e22348293588538689be8c51c23472fd4ca53650b3898401947ef9c7e1a05
LABEL \
    name="cluster-api-provider-agent" \
    com.redhat.component="cluster-api-provider-agent" \
    description="Kubernetes-native declarative infrastructure for agent-based installation. \
    cluster-api-provider-agent serves as infrastructure provider for Kubernetes cluster-api." \
    io.k8s.description="Kubernetes-native declarative infrastructure for agent-based installation. \
    cluster-api-provider-agent serves as infrastructure provider for Kubernetes cluster-api." \
    summary="Kubernetes-native declarative infrastructure for agent-based installation." \
    io.k8s.display-name="cluster-api-provider-agent" \
    io.openshift.tags="mce hypershift cluster-api-provider-agent"
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
